// Next Imports
import type { Metadata } from "next";

// Styles
import "./globals.css";

// Fonts
import localFont from "next/font/local";

// Components
import HeaderSection from "@/components/layout/Header";
import NavbarSection from "@/components/layout/Navbar";
import FooterSection from "@/components/layout/Footer";


// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


// Font
const satoshi = localFont({
  src: [
    {
      path: "../assets/fonts/satoshi/satoshi-light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../assets/fonts/satoshi/satoshi-regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/satoshi/satoshi-medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/fonts/satoshi/satoshi-bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../assets/fonts/satoshi/satoshi-black.otf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-satoshi",
  display: "swap",
});

const integralcf = localFont({
  src: [
    {
      path: "../assets/fonts/integral-cf/integralcf-regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/integral-cf/integralcf-medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/fonts/integral-cf/integralcf-semibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../assets/fonts/integral-cf/integralcf-bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../assets/fonts/integral-cf/integralcf-extrabold.otf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-integralcf",
  display: "swap",
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${satoshi.variable} ${integralcf.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <HeaderSection />
        <NavbarSection /> 
        {children}
        <FooterSection />
      </body>
    </html>
  );
}
